version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7

brews:
  - name: commit-author-refresher
    repository:
      owner: pkarpovich
      name: homebrew-apps
    commit_author:
      name: Pavel Karpovich
      email: pavel.karpovich@outlook.com
    homepage: https://github.com/pkarpovich/commit-author-refresher
    description: Refreshes commit author in git history
    install: |
      bin.install "commit-author-refresher"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"